apiVersion: v1
kind: Service
metadata:
  name: basanta-node-web-app

spec:
  #this defines which pod is represented by this service.
  #the service may be network for other services or
  #for browser
  selector:
    app: node-web-app

  ports:
    - name: http
      port: 80
      targetPort: 5000
